//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadingAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllTemperatureFact
    {
        public Nullable<int> RoomId { get; set; }
        public int ID { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Room Room { get; set; }

        public override string ToString()
        {
            return Temperature + ",";
        }

    }
}
