//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadingAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAGE_AllHumidityFacts
    {
        public string RoomId { get; set; }
        public int ID2 { get; set; }
        public Nullable<decimal> HumidityPercentage { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> AverageHumidityPerMonth { get; set; }
        public Nullable<decimal> AverageHumidityPerYear { get; set; }
    }
}
