//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadingAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Major { get; set; }
        public string Type { get; set; }
        public string Street { get; set; }
        public Nullable<int> StreetNr { get; set; }
        public string City { get; set; }
        public Nullable<int> PostalCode { get; set; }
        public string Country { get; set; }
    }
}
